version: '3.8'
services:
  app:
    build: .
    ports:
      - '5454:5454'
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - .:/usr/src/app
    command: npm start
