version: '3.8'
services:
  app:
    build: .
    ports:
      - "5454:5454"
    environment:
      # Dont modify this env variable 
      - MONGO_URI=mongodb://mongo:27017/busbooking
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
